### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ORCA666** [NoOne-hub/test_resp#2]
Hay mate, it is not an issue related to your code or something, I just want to ask you about something..... 
 so I saw your issue here: https://github.com/FSecureLABS/Ninjasploit/issues/2
But you closed it, did you compile it or it just didn't work ?! 
I am having the same problem these people are not responding to my issues, idk man 
Anyways thanks for your attention and have a nice day !

**Comment by NoOne-hub** [comment]
> Hay mate, it is not an issue related to your code or something, I just want to ask you about something.....
> so I saw your issue here: [FSecureLABS/Ninjasploit#2](https://github.com/FSecureLABS/Ninjasploit/issues/2)
> But you closed it, did you compile it or it just didn't work ?!
> I am having the same problem these people are not responding to my issues, idk man
> Anyways thanks for your attention and have a nice day !

Emm,I compile it successfully,but i don't know how to use it in meterpreter.I use VS2013 to compile it, but just in x86 module. Please tell me if you know how to use it.I send email to you, it contains the compiled binary file. 
If you want to know the way to compile it,you can send email to me.
